<S> = Docs+ (Docs / <Code>)+

<Docs> = (Doc <Empty>+)+
Doc = Title <Empty> (Section <Empty>)+

Title = <"# Fact: "> #".*" <'\n'>
Section = Heading Body
Heading = <"# "> #"\w*" <':'> (<' '> | <'\n'>)

Body = BodySection*
BodySection = BodyMain (BodyContinued | <Empty>)*
<BodyMain> = <"#   ">? #"[A-Z ].*" <'\n'>?
<BodyContinued> = <"# "> <"  ">? #"[a-z].*" <'\n'>?

Empty = #"^#\n" | #"\n"
Code = #".*" | Empty | "" | #"#.*"