<S> = Docs+ (Doc / <Code>)+

<Docs> = (Doc <Empty>+)+
Doc = Title <EmptyComment> (Section)+ 

Title = <"# Fact: "> #".*" <'\n'>
Section = Heading Body
Heading = <"# "> #"\w*" <':'> (<' '> | <'\n'>)

Body = BodySection*
BodySection = BodyMain (BodyContinued | <EmptyComment>)*
<BodyMain> = <"#   ">? #"[A-Z ].*" <'\n'>?
<BodyContinued> = <"# "> <"  ">? #"[a-z'`\"].*" <'\n'>?

Empty = #"\n"
EmptyComment = #"^#\n"
Code = #".*" | Empty | "" | #"#.*" | Epsilon