(* Attempt 2 at the BNF description for inline fact docs *)
<S> = Docs <Code>+
Docs = (Doc <Empty>+)+
Doc = Title <Empty> (Section <Empty>)+
Title = <"# Fact: "> #".*" <'\n'>
Section = Heading Body
Heading = <"# "> #"\w*" <':\n'>
Body = (BodyMain BodyContinued*)*
BodyMain = <"#   "> #"[A-Z].*" <'\n'>
BodyContinued = <"# "> #"[a-z].*" <'\n'>


Empty = #"^#\n" | #"\n"
Code = #".*" | Empty | "" | #"#.*"